apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.20.1
      # helm:
      #   valueFiles:
      #     - $values/gitops/istio/values/istiod.yaml
    # - repoURL: "https://github.com/rifqoi/xendok-infra.git"
    #   targetRevision: HEAD
    #   ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
