apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.20.1
      helm:
        valueFiles:
          - $values/gitops/istio/values/istio-base.yaml
    - repoURL: "https://github.com/rifqoi/xendok-infra.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # To ignore https://github.com/argoproj/argo-cd/issues/9323
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
